### ISSUE TITLE
Obtener Sprites

### ISSUE THREAD

**Issue by hpneo** [hpneo/bomberman#1]
- [Sprites inspirados en Bomberman](http://gamedevelopment.tutsplus.com/articles/enjoy-these-totally-free-bomberman-inspired-sprites--gamedev-8541)
- [Bomberman para Android](http://www.spriters-resource.com/mobile/bombermanforandroid/)

**Comment by swbvelasquez** [comment]
Aquí hay algunos sprites, estamos usando la opción 6 por defecto pero si se consiguen mejores sprites postearlo y avisar.

Opcion 1:
http://tsgk.captainn.net/?p=showsheets&t=sr&sr=121

Opcion 2:
https://scratch.mit.edu/projects/17206438/#player

Opcion 3:
http://spritedatabase.net/game/928

http://spritedatabase.net/game/5

http://spritedatabase.net/game/529

http://spritedatabase.net/file/8518

Opcion 4:
http://photobucket.com/images/bomberman%20sprite%20sheet

Opcion 5:
http://www.spriters-resource.com/snes/sbomber3/

Opcion 6:
http://www.spriters-resource.com/
http://www.spriters-resource.com/search/?q=Bomber
http://www.spriters-resource.com/mobile/bombermanforandroid/sheet/70078/

Opcion 7:
http://opengameart.org/art-search?keys=bomberman

Opcion 8:
http://kenney.nl/assets?s=bomberman
http://opengameart.org/art-search-advanced?field_art_tags_tid=bomb

Opcion Complementaria:
http://randomhoohaas.flyingomelette.com/Sprites/spr-bomberman.php

**Comment by swbvelasquez** [comment]
Necesitamos un boton de inicio, un par mas para jugar, imágen de vidas o algo similar, entre otras cosas.
